print("Hello world")
print("Hello Costa")
print("Costa made a rebase")
print("Costa will make a cherry-pick")
print("Bras made a merge")
print("Bras made a rebase")
print("Bras made a cherry-pick")
print("Carriço made a merge")
print("Carriço made a rebase")
print("carrico made a cherry-pick")
